### ISSUE TITLE
Initialising GUI/Editors

### ISSUE THREAD

**Issue by GolddolphinSKB-Fexcraftian** [Fexcraft/FMT-Standalone#1]
Steps to recreate:
- Start program
- Create shapebox/box
- Open Shapelist (Shapebox is auto highlighted)
- Open Generic editor

The values do not show up until clicking on the Shapebox in the shapelist to deselect and select again.

**Comment by Fexcraft** [comment]
🤔 kinda know issue although I thought I fixed most of it.
