### ISSUE TITLE
Weird clipping plane with GUI

### ISSUE THREAD

**Issue by GolddolphinSKB-Fexcraftian** [Fexcraft/FMT-Standalone#2]
Viewport seems to cover whole screen.

[Yee](https://cdn.discordapp.com/attachments/365628561819697162/501776805804376064/Screen_Shot_2018-10-16_at_16.20.20.PNG)

Viewport should possibly be resized from the GUI editors brought up?

**Comment by Fexcraft** [comment]
How you managed to do that 0.o

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Fly into the cube, so the faces go through the viewport.

**Comment by Fexcraft** [comment]
On quick research it seems not to be something "easy" fixable, due to how things are rendered/GL.

**Comment by Fexcraft** [comment]
Uhm, I guess #9 fixed it.
